/// Generates a short, typable trip code.
///
/// Six characters from a set with no 0/O/1/I/L in it. That exclusion is the
/// whole design: a code read aloud across a table ("that's B-K-four-J-eight")
/// has to survive being spoken and typed by two people who have never met. A
/// code containing a zero and an O is read wrong roughly every other time, and
/// the fix — retyping the code — happens over a shared dinner table.
///
/// WHAT IT IS NOT. The code identifies a trip so friends can confirm they are
/// looking at the same one. It does not sync anything, join anyone to a room,
/// or transmit a byte. Two people typing the same code are still two phones with
/// two copies of the data, which is the deal the whole app is built on.
library;

import 'dart:math';

/// No 0/O/1/I/L — every excluded glyph is a pair that gets misread aloud.
const String _alphabet = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

const int _defaultLength = 6;

/// A random code, e.g. `BK4J8Q`.
///
/// Six characters over a 31-symbol alphabet is about 30 bits, so two trips
/// generated by chance collide with negligible probability — and it does not
/// need to be unique anyway, since nothing is looked up by code. It is a thing
/// to read out loud, not a key.
String generateTripCode({int length = _defaultLength, Random? random}) {
  final rng = random ?? Random();
  final buffer = StringBuffer();
  for (var i = 0; i < length; i++) {
    buffer.write(_alphabet[rng.nextInt(_alphabet.length)]);
  }
  return buffer.toString();
}

/// Whether [code] could have been produced here: right length and alphabet.
///
/// Used to tell a user they typed it wrong. Deliberately not a lookup — there is
/// nothing to look up, because the code does not address anything on a server.
bool isPlausibleTripCode(String code) {
  if (code.length != _defaultLength) return false;
  return code.toUpperCase().split('').every(_alphabet.contains);
}
